### PR TITLE
port to GtkApplication

### PR DESCRIPTION
**Pull request by mbkma**
see https://gitlab.gnome.org/GNOME/gnome-system-monitor/-/commit/aa625d19e7b72587f70fb18dc3dcfcdba528533e

### CODE REVIEW

**Review by lukefromdc — APPROVED** [review]
Builds and runs fine. Tested terminating a process from a running session of this, worked same as before. A second invocation while an existing instance is running simply brings the existing instance to the foreground, then exits. This is the same behavior as before, so no surprises there

**Comment by raveit65** [comment]
Only a rebase with master.

**Comment by lukefromdc** [comment]
What is the status of this?

**Review by raveit65 — APPROVED** [review]
LGTM,
m-s-m runs fine for several days and changes are similar to g-s-m one.
It's only possible to start on instance of m-s-m which is the expected behavior, and i noticed no regression so far.

**Comment by raveit65** [comment]
@mbkma 
There is a conflict with master.

**Pull request merged**
