### PR TITLE
Use g_date_time_format instead of filter_date

### PR DESCRIPTION
**Pull request by rbuj**
https://developer.gnome.org/glib/stable/glib-GDateTime.html#g-date-time-format

### CODE REVIEW

**Comment by rbuj** [comment]
TEST:
Select **Processes** tab, right-click on any process, select **Properties**. `procman_format_date_for_display` is used in **Started** property.

**Comment by lukefromdc** [comment]
While I do get a date on this, it is "today" both with this and with master, as my machines are never left running overnight. Thus I can't test long-running anything, as an encrypted computer left running unattended is vulnerable to the cold boot attack.

**Comment by lukefromdc** [comment]
I did get these two style warnings from cppcheck:

src/e_date.c
 line 65 scope of variables 'buf' can be reduced
 line 66 scope of variable 'sp' can be reduced

**Comment by lukefromdc** [comment]
I did get these two style warnings from cppcheck (EDIT-these are in master and are FIXED by this PR, which removes the offending lines):

src/e_date.c
 line 65 scope of variables 'buf' can be reduced
 line 66 scope of variable 'sp' can be reduced

**Pull request merged**
