### PR TITLE
Linux: Use /proc/meminfo instead of glibtop/mem.h, glibtop/swap.h

### PR DESCRIPTION
**Pull request by rbuj**
To achieve the same results obtained with free/top on Linux.
https://gitlab.com/procps-ng/procps/blob/master/

Screenshot:

Captura de pantalla a 2019-04-22 02-37-12

### CODE REVIEW

**Comment by bdejean** [comment]
Hello, SReclaimable is already included in MemAvailable that is provided by Linux >= 3.14 is providing a memavailable field that shows what's really available to user. So I don't think your change makes sense.

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773
https://gitlab.gnome.org/GNOME/libgtop/blob/master/sysdeps/linux/mem.c

**Comment by rbuj** [comment]
- Slab: In-kernel data structures cache
- SReclaimable: The part of the Slab that might be reclaimed (such as caches)

[libgtop](https://gitlab.gnome.org/GNOME/libgtop/blob/master/sysdeps/linux/mem.c#L63):
```C
buf->user = buf->total - get_scaled(buffer, "MemAvailable:");
```
[procps-ng](https://gitlab.com/procps-ng/procps/blob/master/proc/sysinfo.c#L789)
```C
kb_main_cached = kb_page_cache + kb_slab_reclaimable;
mem_used = kb_main_total - kb_main_free - kb_main_cached - kb_main_buffers;
```
Example
```
$ cat /proc/version
Linux version 5.0.8-300.fc30.x86_64 (mockbuild@bkernel03.phx2.fedoraproject.org) (gcc version 9.0.1 20190312 (Red Hat 9.0.1-0.10) (GCC)) #1 SMP Wed Apr 17 16:55:36 UTC 2019
$ cat /proc/meminfo 
MemTotal:        3071048 kB
MemFree:         2318756 kB
MemAvailable:    2656348 kB
Buffers:           99364 kB
Cached:           354932 kB
SwapCached:            0 kB
Active:           278736 kB
Inactive:         293464 kB
Active(anon):     127332 kB
Inactive(anon):     4340 kB
Active(file):     151404 kB
Inactive(file):   289124 kB
Unevictable:       19092 kB
Mlocked:           19092 kB
SwapTotal:       3203068 kB
SwapFree:        3203068 kB
Dirty:               608 kB
Writeback:             0 kB
AnonPages:        136984 kB
Mapped:           212096 kB
Shmem:              5056 kB
KReclaimable:      65532 kB
Slab:             128440 kB
SReclaimable:      65532 kB
SUnreclaim:        62908 kB
KernelStack:        3632 kB
PageTables:         5184 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     4738592 kB
Committed_AS:    1034156 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
Percpu:             1032 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:      106432 kB
DirectMap2M:     3039232 kB
```
Test:
```shell
export MemTotal=3071048
export MemFree=2318756
export MemAvailable=2656348
export Buffers=99364
export Cached=354932
export Slab=128440
export SReclaimable=65532
$ echo $MemTotal - $MemAvailable | bc
414700
$ echo $MemTotal - $MemFree - $Cached - $SReclaimable - $Buffers | bc
232464
```

**Comment by bdejean** [comment]
You can see in Linux commit itself that MemAvailable already includes SReclaimable. So procps trying to outsmart the kernel gives wrong values.

**Comment by rbuj** [comment]
Linux Kernel: MemAvailable doesn't consider Buffers as reclamable space? Really?

**Comment by rbuj** [comment]
Linux removes the memory used by the system from total memory.
```shell
$ dmesg | grep -in memory
...
Memory: 3042020K/3145272K available (12291K kernel code, 1523K rwdata, 4020K rodata, 2204K init, 4688K bss, 103252K reserved, 0K cma-reserved)
...
... Freeing unused kernel image memory: ...
...
```
Fields in /proc/meminfo:
- Total memory = DirectMap4k + DirectMap2M
- Total usable memory (excluding used by the system) = MemTotal
- The amount of physical memory not used by the system = MemFree
- An estimate of how much memory is available for starting new applications, without swapping: MemAvailable

MemUsed = MemTotal - MemFree - Buffers - Cached - Slab

- MemTotal != DirectMap4k + DirectMap2M
- MemFree != MemAvailable
- MemUsed != MemTotal - MemAvailable (memory not available for starting new applications)

Ref https://access.redhat.com/solutions/406773

**Comment by lukefromdc** [comment]
I don't know enough about the kernel to further evaluate this

**Comment by rbuj** [comment]
### Memory used: gnome-system-monitor vs mate-system-monitor vs top
mate-system-monitor using libgtop like gnome-system-monitor does:

A comparison of the results showed no noticeable difference between mate-system-monitor & gnome-system-monitor, there is an offset in adquision time. top displays a lower value.

Captura de pantalla a 2019-04-24 11-55-46

mate-system-monitor using procps-ng's memory-used formula:

A comparison of the results showed no noticeable difference between mate-system-monitor & top. gnome-system-monitor displays a higher value.

Captura de pantalla a 2019-04-24 12-02-15

**Comment by bdejean** [comment]
Well, gnome-system-monitor uses directly libgtop and displays as used the total - available. When the kernel gives us a MemAvailable, i tend to believe it. And i think that considering that the memory usage is the total minues this MemAvailable makes sense.

**Comment by lukefromdc** [comment]
If we already depend on  libgtop anyway for any other reason, is there any real reason to bother with splitting just this out, on Linux only? Main value is using something directly may be a shorter code path at runtime, but disadvantage is we could have to watch for future kernel changes ourselves

**Comment by rbuj** [comment]
```shell
$ free
              total        used        free      shared  buff/cache   available
Mem:        3071048      569472     2385652       25820      115924     2346928
Swap:             0           0           0
```
total = used + free + buff/cache
```shell
$ echo "569472 + 2385652 + 115924" | bc
3071048
```
used = total - free - buff/cache

MemAvailable it's only for malloc purpose. Test:
```shell
g++ -o test -Wall test.cpp
sudo swapoff -a && ./test && swapoff -a && swapon -a
```
```C
#include <iomanip>
#include <iostream>
#include <fstream>
#include <sstream>
#include <string.h>
#include <unistd.h>
#include <cstdlib>

using namespace std;

int main()
{
    unsigned long memavailable = 0ULL;
    std::ifstream ifs("/proc/meminfo");
    std::stringstream buffer;
    std::string line;
    unsigned int seconds = 60ULL;

    buffer << ifs.rdbuf();
    while (std::getline(buffer, line)) {
        std::istringstream iss(line);
        unsigned long meminfo_value;
        string meminfo_label, meminfo_unit;
        iss >> meminfo_label >> meminfo_value >> meminfo_unit;
        if (meminfo_label == "MemAvailable:")
            memavailable = meminfo_value;
    }
    memavailable *= 1024;
    cout << "MemAvailable: " << std::setfill(' ') << std::setw(12) << memavailable << " bytes" << endl;

    char* pData = (char*) calloc (memavailable,sizeof(char));
    for (unsigned long i=0;i<memavailable;i++)
        pData[i]='a';

    buffer.clear();
    ifs.close();
    ifs.clear();
    ifs.open("/proc/meminfo");
    buffer << ifs.rdbuf();
    while (std::getline(buffer, line)) {
        std::istringstream iss(line);
        unsigned long meminfo_value;
        string meminfo_label, meminfo_unit;
        iss >> meminfo_label >> meminfo_value >> meminfo_unit;
        if (meminfo_label == "MemAvailable:")
            memavailable = meminfo_value;
    }
    memavailable *= 1024;
    cout << "MemAvailable: " << std::setfill(' ') << std::setw(12) << memavailable << " bytes" << endl;

    cout << "wait " << seconds << " seconds" << endl;
    sleep(seconds);
    free(pData);

    return 0;
}
```

**Comment by raveit65** [comment]
I am really undecided, but personal i would prefer to use libgtop if it does the same.
Because i am using fedora  with very new kernel, and i am the first one who will get annoying bug reports in my mail box when something is changed with a new kernel.

**Comment by sc0w** [comment]
Maybe it can be added a gsettings key to make happy everybody

**Comment by flexiondotorg** [comment]
I'd prefer to avoid platform specific implementations when a well known library exists.

I don't see any end user benefit by adding this code but only additional code to maintain into the future.

**Pull request closed without merging**
