### PR TITLE
Fix 'msgstr' is not a valid C format string, unlike 'msgid'

### LINKED ISSUE #185: Build issue with a lot of languages
#### Expected behaviour
Builds fine after latest pull from transifex.

#### Actual behaviour
Build failed after latest pull from transifex.

#### Steps to reproduce the behaviour
At master:
git revert https://github.com/mate-desktop/mate-system-monitor/commit/9bf50956e8e355ebfe576220977ff88782273fe7
./autogen.sh && make
Building failed with
```
be.po:888: 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: The character that terminates the directive number 1 is not a valid conversion specifier.
be.po:893: 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: The character that terminates the directive number 1 is not a valid conversion specifier.
/usr/bin/msgfmt: found 2 fatal errors
be.po: 298 translated messages, 31 untranslated messages.
make[3]: *** [Makefile:203: be.gmo] Error 1
```
This happens with 29 languages at the place!

#### MATE general version
1.23

#### Package version
1.23.0

#### Linux Distribution
All

#### Link to downstream report of your Distribution
1.23.1 isn't build in any distro, so there aren't downstream reports.

I fixed building with https://github.com/mate-desktop/mate-system-monitor/commit/9bf50956e8e355ebfe576220977ff88782273fe7 for generating 1.23.1 release.
But this will be override by next pull from transifex. So we need a real fix for it.
I assume it is a problem in our code because it affect a lot of languages.

### PR DESCRIPTION
**Pull request by rbuj**
Closes #185

```shell
declare -i LINE

rm po/*.po
tx pull -a

FILE=mate-system-monitor.pot
LINE=$(fgrep -n "msgid \"Width of process '% CPU' column\"" $FILE | cut -d':' -f1)
LINE=$LINE-1
echo "sed -i '"$LINE"d' $FILE" | sh
LINE=$(fgrep -n "msgid \"Show process '% CPU' column on startup\"" $FILE | cut -d':' -f1)
LINE=$LINE-1
echo "sed -i '"$LINE"d' $FILE" | sh

for FILE in po/*.po;
do
  LINE=$(fgrep -n "msgid \"Width of process '% CPU' column\"" $FILE | cut -d':' -f1)
  LINE=$LINE-1
  echo "sed -i '"$LINE"d' $FILE" | sh
  LINE=$(fgrep -n "msgid \"Show process '% CPU' column on startup\"" $FILE | cut -d':' -f1)
  LINE=$LINE-1
  echo "sed -i '"$LINE"d' $FILE" | sh
done

for t in po/*.po; do echo "$(basename "$t" .po)"; done | sort > po/LINGUAS
sed -i '1s/^/# please keep this list sorted alphabetically\n#\n/' po/LINGUAS
```
Catalan screeshot:

Captura de pantalla a 2020-01-23 09-40-30

### CODE REVIEW

**Comment by cwendling** [comment]
This doesn't seem like a real fix but a temporary workaround, isn't it?  Looks like re-extracting the translations form the gsettings file would break this again, wouldn't it?

**Comment by rbuj** [comment]
It's just a temporary workaround. Yes, `./makepot` will override the fix on pot file, but we should only edit the pot file until someone fixes gettext.

**Comment by raveit65** [comment]
This fixes the build but `make` creates a new resource file `po/mate-system-monitor.pot` which has the same bad `c-format` lines.
```
#: src/org.mate.system-monitor.gschema.xml.in:288
#, c-format
msgid "Width of process '% CPU' column"
msgstr ""

#: src/org.mate.system-monitor.gschema.xml.in:292
#, c-format
msgid "Show process '% CPU' column on startup"
msgstr ""
```
That means our `./makepot` script
```
# normal translations for the package
make -C po $PACKAGE.pot && mv po/$PACKAGE.pot .
```
generates the same issue which we push to transifex, and a new pull from transifex breaks building again.

The question is why those entries have the `c-format` or which part in our code is responsible for this?

**Comment by raveit65** [comment]
> but we should only edit the pot file until someone fixes gettext.

We can add a sed command to ./makepot to remove `c-format` from mate-system-monitor.pot, or not?

Than this band aid is good for me , until we find the right cause.

**Comment by raveit65** [comment]
@rbuj @cwendling 
I am fine with adding `sed -i "/#, c-format/d" $PACKAGE.pot` to make.pot, to avoid this problem when creating tarballs for 1.24 release the next week.
```
# normal translations for the package
make -C po $PACKAGE.pot && mv po/$PACKAGE.pot .
sed -i "/#, fuzzy/d" $PACKAGE.pot
sed -i "/#, c-format/d" $PACKAGE.pot
```

**Comment by cwendling** [comment]
@raveit65 we probably should not just remove *all* `c-format` markers, and definitely not all `fuzzy` ones.

**Comment by raveit65** [comment]
@cwendling 
Why?
Any argument?
we remove `fuzzy` lines to avoid unneeded warnings with older distros.
Please follow other topics where this was decided.

Removing `c-format markers` is needed to push this shiti things again to transifex.
It doesn't hurt to remove this.
You have all the time to fix this problems in a proper way, but i like to release Mate 1.24 in February.
And i don't have the time to run again in those problems.

**Comment by raveit65** [comment]
@cwendling 
Please open an report about not removing `fuzzy` lines where you can discuss this with @sc0w 
This isn't related to this PR.

**Comment by cwendling** [comment]
> Why?
> Any argument?
> we remove fuzzy lines to avoid unneeded warnings with older distros.

Removing fuzzy translations is fine, but just the fuzzy flag would result in enabling the fuzzy translations, which might be wrong or worse.  I admit I didn't follow the other discussions though.

> Removing `c-format` markers is needed to push this shiti things again to transifex.
> It doesn't hurt to remove this.

Yes, this is not dangerous, but it prevents Gettext from checking the translated format strings are correct, which could hide nasty bugs.  I got bit by that in the past.
However, as a temporary workaround, why not.

**Comment by raveit65** [comment]
> Removing fuzzy translations is fine, but just the fuzzy flag would result in enabling the fuzzy translations, which might be wrong or worse. I admit I didn't follow the other discussions though.

It is already fixed with gettext-0.20.0 which is used by most distros.
Only debian users will have the pain with that compiling warnings  when we remove that line ;)
but this should discussed in a new report with @sc0w

**Comment by rbuj** [comment]
@raveit65 makepot filters-out conflictive c-format comments

example:
```
[robert@localhost ~]$ cat 2
a

#. makepot: remove comment
#: src/org.mate.system-monitor.gschema.xml.in:33
#, c-format
c

#: src/org.mate.system-monitor.gschema.xml.in:33
#, c-format
c
[robert@localhost ~]$ perl -0777 -p -e 's/#. makepot: remove comment\n#\: src\/org\.mate\.system\-monitor\.gschema\.xml\.in\:([0-9]*)\n#, c-format\n/#\: src\/org\.mate\.system\-monitor\.gschema\.xml\.in\:\1\n/s'  2
a

#: src/org.mate.system-monitor.gschema.xml.in:33
c

#: src/org.mate.system-monitor.gschema.xml.in:33
#, c-format
c
```

**Comment by yetist** [comment]
I see that the line contains "% CPU" just a summary of the configuration items. Maybe we can modify this summary to fix it?

**Comment by raveit65** [comment]
> I see that the line contains "% CPU" just a summary of the configuration items. Maybe we can modify this summary to fix it?

I will merge this PR for 1.14 release when we don't find another solution.

**Comment by lukefromdc** [comment]
I assume you mean 1.24 release, not 1.14 of course

**Pull request merged**
