### PR TITLE
Be consistent with top on used memory

### PR DESCRIPTION
**Pull request by pyhalov**

### CODE REVIEW

**Comment by pyhalov** [comment]
I've tried to find out, why vmstat and top shows ~ 3 GB used memory on OpenIndiana and mate-system-monitor - only  about 600 MB. Found that it show not used, but user memory. Is it intentional?

**Comment by bdejean** [comment]
Yes, that's what we want because with a modern OS, your memory tends to be 100% used by VM cache, ZFS ARC, etc. Then it only means that glibtop_get_mem can be improved on OpenIndiana. I had done for FreeBSD.

**Comment by rbuj** [comment]
@pyhalov you can also keep the support for GNU/Linux :)
```diff
diff --git a/src/load-graph.cpp b/src/load-graph.cpp
index 610a349..22ea428 100644
--- a/src/load-graph.cpp
+++ b/src/load-graph.cpp
@@ -375,11 +375,19 @@ get_memory (LoadGraph *graph)
 
     /* There's no swap on LiveCD : 0.0f is better than NaN :) */
     swappercent = (swap.total ? (float)swap.used / (float)swap.total : 0.0f);
+#ifndef __linux__
     mempercent  = (float)mem.used  / (float)mem.total;
 
     set_memory_label_and_picker(GTK_LABEL(graph->labels.memory),
                                 GSM_COLOR_BUTTON(graph->mem_color_picker),
                                 mem.used, mem.total, mempercent);
+#else
+    mempercent  = (float)mem.user  / (float)mem.total;
+
+    set_memory_label_and_picker(GTK_LABEL(graph->labels.memory),
+                                GSM_COLOR_BUTTON(graph->mem_color_picker),
+                                mem.user, mem.total, mempercent);
+#endif
 
     set_memory_label_and_picker(GTK_LABEL(graph->labels.swap),
                                 GSM_COLOR_BUTTON(graph->swap_color_picker),
```
@pyhalov, @bdejean You may also be interested on https://github.com/mate-desktop/mate-applets/pull/493

**Comment by raveit65** [comment]
Any progress?

**Comment by raveit65** [comment]
NO action since several years , closing.
Hit me if this is wrong.

**Pull request closed without merging**
