### PR TITLE
Fix openSUSE Tumbleweed rolling release info

### PR DESCRIPTION
**Pull request by rbuj**
```sh
$ cat os-release
NAME="openSUSE Tumbleweed"
# VERSION="20190314"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20190314"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20190314"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
```

### CODE REVIEW

**Comment by rbuj** [comment]
opensuse

**Comment by sc0w** [comment]
@rbuj Thanks! this PR fixes the same issue in debian (and probably in more distros)

Screenshot at 2019-03-17 20-39-04

**Comment by rbuj** [comment]
@sc0w 
Do you want to show **buster/sid** in Release?

sid

```patch
diff --git a/src/sysinfo.cpp b/src/sysinfo.cpp
index 273f2f9..7abb1ad 100644
--- a/src/sysinfo.cpp
+++ b/src/sysinfo.cpp
@@ -552,6 +552,15 @@ namespace {
                     }
                 }
             }
+            if (this->distro_release.empty()) {
+                // Debian GNU/Linux sid
+                input.close();
+                input.clear();
+                input.open("/etc/debian_version");
+                if (input) {
+                    getline(input, this->distro_release);
+                }
+            }
         }
     };
 
```

**Comment by sc0w** [comment]
@rbuj great tip!

**Comment by rbuj** [comment]
@sc0w do it yourself

**Pull request merged**
