### PR TITLE
Fix system logo alignment

### PR DESCRIPTION
**Pull request by sc0w**
Fixes https://github.com/mate-desktop/mate-system-monitor/issues/93

### CODE REVIEW

**Comment by monsta** [comment]
Looks better now. I have a Mint logo here though.

m-s-m-logo

Previously it was in the upper left corner. That's weird, because the padding is now *decreased* to zero, not increased.

**Comment by monsta** [comment]
Small typo: alig**n**ment 🙂

**Comment by monsta** [comment]
Ah, I see. It's the alignment of the colored background. The logo itself is at the same place.

Before:

logo-1

After:

logo-2

**Comment by sc0w** [comment]
@monsta 

> Small typo: alignment

ok, done

**Comment by monsta** [comment]
Dammit, I had the previous version here, so now the commit with typo is merged. Sorry 😞

**Comment by sc0w** [comment]
no problem

for the record, merged with https://github.com/mate-desktop/mate-system-monitor/commit/c3a2692d4e97e1bd699bba885a0b7be11f93bc89

**Pull request closed without merging**
