### PR TITLE
Network History: Fix labels

### PR DESCRIPTION
**Pull request by rbuj**
Don't show "/s" in total sent/received data
Fix values in Show network speed in bits

### CODE REVIEW

**Comment by lukefromdc** [comment]
I am not duplicating the issue being fixed here if I am reading it correctly. Here's what I get from master right now:

Network_History


:

**Comment by sc0w** [comment]
I see the same as @lukefromdc , no issue without this PR




it seems we see MiB instead MB

How to change MiB to MB ?

**Comment by lukefromdc** [comment]
OK, it looks like what we just fixed is a corner-case bug, my suspicion is maybe language related? Still needed to be fixed. MiB and MB mean two different things, one in which a megabyte is 1024 kilobytes of 1024 bytes each (binary) and the other in which a megabyte is only 1000 kilobytes of 1000 bytes each(decimal). Needless to say, hard drive makers list decimal capacity.

**Comment by sc0w** [comment]
see the screenshots (without this PR), with `network-in-bits` gsettings key disabled:



and `network-in-bits` enabled:



I have no idea how to see with GB / MB instead GiB / MiB

**Comment by lukefromdc** [comment]
Where is that gsettings key? I don't see it in dconf-editor, though note that I use an old version that does not support relocatable schemas

**Comment by lukefromdc** [comment]
OK I found it, it was buried under all the CPU color key and though it is a bit fiddly (sometimes I had to move to another line in dconf-editor or restart mate-system-monitor), it works both before and after this PR was merged. Changing it will show you either MiB or Mb (megabits), an option that probably exists because some network speeds are defined that way but capped bandwidth is normally defined in MB or GB(no doubt by the decimal version). I do NOT see an option to use binary or decimal KB/MB/GB however

**Comment by raveit65** [comment]
What's the dconf schema name of it?

**Comment by raveit65** [comment]
Found it, and it looks correct with PR :)
Bildschirmfoto zu 2019-04-20 23-39-30

**Comment by sc0w** [comment]
My comment was because I don't understand why you see MB and we (me and @lukefromdc ) see M**i**B

**Comment by raveit65** [comment]
```
[rave@mother ~]$ gsettings get org.mate.system-monitor network-in-bits
true
```

**Pull request merged**
