### PR TITLE
Use a blank line at most

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Review by raveit65 — APPROVED** [review]
LGTM

**Comment by raveit65** [comment]
@rbuj 
This breaks debian build for some reasons. Please fix.
https://app.travis-ci.com/github/mate-desktop/mate-system-monitor/jobs/551834353#L2222

**Comment by rbuj** [comment]
@raveit65 the build error comes from compiler's valarray:
https://github.com/freedesktop/cairomm/blob/393cd568894d1f07858ed9945022b7964635f9f8/cairomm/context.h#L31

**Comment by raveit65** [comment]
@rbuj 
So, someone who understand this this error should file out a report there.
Should we disable debian for travis-ci ?
I suspect building will fail for every other build in master or any PR.
Can you please trigger a build at https://github.com/mate-desktop/mate-system-monitor/pull/229 for testing?
But first please without a rebase from master to be shure.

**Comment by rbuj** [comment]
> @rbuj So, someone who understand this error should file out a report there.

the error will disappear when cairomm is rebuilt

> Can you please trigger a build with #229 for testing? But first please without a rebase from master to be sure.

ok

**Comment by rbuj** [comment]
culprit https://github.com/gcc-mirror/gcc/commit/91bac9fed5d082f0b180834110ebc0f46f97599a#diff-3ca014b30837a35dd0f8881b5ed55263166a8ff9e57fa145a4829fd735c1fdc8

**Pull request merged**
