### PR TITLE
sysinfo: avoid adding a device more than once such as for brtfs

### PR DESCRIPTION
**Pull request by rbuj**
In the example below, the available disk space is counted twice before the change.
Screenshot at 2020-11-15 17-07-57
Screenshot at 2020-11-15 17-09-35

After

Screenshot at 2020-11-15 17-09-06

### CODE REVIEW

**Review by lukefromdc — APPROVED** [review]
On my system (no btrfs filesystems) I get the same number of filesystems shown either way, but this built and ran fine, with no new (to my system) warnings in terminal from running the built binary in place from terminal. No ugly surprises so OK on this end

**Comment by raveit65** [comment]
This is very confusing. In a fresh f33 default installation a screenshot with mate-system-monitor, gnome-disks and blivet-gui.
Bildschirmfoto zu 2020-11-20 14-33-04
Displaying the same partition as `/` and `/home` is definitely wrong.
Gnome-disks displays it as `/` partition which is correct.
I am still wondering that using only a root partition is the default in fedora now. That is new for me.
I didn't test PR right now, but did you fix naming it as /home directory ?

**Comment by rbuj** [comment]
> Displaying the same partition as `/` and `/home` is definitely wrong.

No, I don't think it's wrong.

The partition layout of sda disk has 2 partitions, sda1 and sda2:
```
$ lsblk 
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda      8:0    0   60G  0 disk 
├─sda1   8:1    0    1G  0 part /boot
└─sda2   8:2    0   59G  0 part /home
sr0     11:0    1 1024M  0 rom  
zram0  252:0    0    4G  0 disk [SWAP]
```
- sda1, it's a small ext4 partition (about 1GB) for booting the system which is mounted in the /boot mounting point
- sda2: it's a big btrfs partition (about 59GB)  which has tho subvolumes: `/` and `/home`.
```
$ sudo btrfs filesystem show 
Label: 'fedora_localhost-live'  uuid: 5f5bb237-406b-47f1-99dd-a11ce664cd6c
	Total devices 1 FS bytes used 20.08GiB
	devid    1 size 59.00GiB used 28.02GiB path /dev/sda2

$ sudo btrfs subvolume list /
ID 256 gen 76431 top level 5 path home
ID 257 gen 76492 top level 5 path root
ID 268 gen 75614 top level 257 path var/lib/machines
```

Captura de Pantalla 2020-11-20 a les 17 23 14

**Comment by raveit65** [comment]
Forget about  /boot (/dev/vda1) (ext4) partition.
In my screenshot of mate-system-monitor `/dev/vda2` is displays twice as `/`  and `/home`.
This is without PR.
I will test PR to see if it make  a different.

And i think that this tool (lsblk) is wrong.
It displays the `/` partition as /home.
The whole qemu VM disk is about 20GB.
```
[rave@localhost ~]$ lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sr0     11:0    1    2G  0 rom  /run/media/rave/Fedora-MATE-Live-33-1-2
zram0  251:0    0  3,9G  0 disk [SWAP]
vda    252:0    0   20G  0 disk 
├─vda1 252:1    0    1G  0 part /boot
└─vda2 252:2    0   19G  0 part /home
```
I mean why there is a /home partition but no main `/`partition?

Ok, gparted displays /dev/vda1 partition with 2 mount points, `/home` and `/`.
But gnome-disks stated it as `mounted as root`.
And blivet-gui seems confused as it displays no mount point.
This looks for me that all that tools are not synced with the new fedora default.

Fedora btrfs guys asked me some month ago to use btrfs as default for f33 MATE-Compiz spin. I will ask them to clarify the situation.

**Comment by raveit65** [comment]
Hmm,
```
[root@localhost rave]# cat /etc/fstab 

#
# /etc/fstab
# Created by anaconda on Fri Nov 20 07:55:14 2020
#
# Accessible filesystems, by reference, are maintained under '/dev/disk/'.
# See man pages fstab(5), findfs(8), mount(8) and/or blkid(8) for more info.
#
# After editing this file, run 'systemctl daemon-reload' to update systemd
# units generated from this file.
#
UUID=a66b16a6-4051-405f-b3f9-9820b1da85c2 /                       btrfs   subvol=root     0 0
UUID=1373a9e5-e488-4d08-b0c1-71007d8212b9 /boot                   ext4    defaults        1 2
UUID=a66b16a6-4051-405f-b3f9-9820b1da85c2 /home                   btrfs   subvol=home     0 0
```
Ok, what system-monitor displays seems to be correct.
But why is the same btrfs subvol mounted twice?

**Comment by rbuj** [comment]
btrfs is a tree based filesystem which allows you to create snapshots quickly.
More info https://btrfs.wiki.kernel.org/index.php/SysadminGuide#Subvolumes

**Comment by raveit65** [comment]
I think we should mark the partitions as btrfs-subvolumes in mate-system-monitor, in opposite to normal block devices.
There are people like me who use a multiboot system with several root devices for several linux installations.

**Comment by rbuj** [comment]
I don't think it's necessary. Note gnome-disks doesn't display the logical view and only displays 1 mounting point. blivet-gui doesn't display the mounting points for btrfs subvolumes.

Test: btrfs pool of 2 devices (/dev/sdb, /dev/sdc) + subvolume + snapshot (RAID1: 8GB+8GB=16GB)
(additional test: mountlist provided by libgtop)
```
sudo mkfs.btrfs /dev/sdb /dev/sdc
sudo mkdir /pool
sudo mount -t btrfs /dev/sdb /pool
sudo btrfs subvolume create /pool/new_subvol
sudo btrfs subvolume snapshot /pool /pool/snapshot_of_root
sudo mount -t btrfs -o subvol=new_subvol /dev/sdb /pool/new_subvol
sudo mount -t btrfs -o subvol=snapshot_of_root /dev/sdb /pool/snapshot_of_root

wget https://raw.githubusercontent.com/GNOME/libgtop/master/examples/mountlist.c
sed -i '1s/^/#include <unistd.h>/' mountlist.c
gcc -Wall -DGTOPLOCALEDIR=\"/usr/share/locale\" -DGETTEXT_PACKAGE=\"libgtop\" -std=gnu99 mountlist.c `pkg-config --cflags --libs glib-2.0 libgtop-2.0` -o mountlist
./mountlist
```

VirtualBox_9 Fedora 33_20_11_2020_23_54_21

```
[robert@localhost ~]$ sudo btrfs filesystem show
Label: 'fedora_localhost-live'  uuid: 5f5bb237-406b-47f1-99dd-a11ce664cd6c
	Total devices 1 FS bytes used 20.22GiB
	devid    1 size 59.00GiB used 28.02GiB path /dev/sda2

Label: none  uuid: d223c488-12be-49ff-8b69-79b2861a840f
	Total devices 2 FS bytes used 224.00KiB
	devid    1 size 8.00GiB used 272.00MiB path /dev/sdb
	devid    2 size 8.00GiB used 264.00MiB path /dev/sdc

[robert@localhost ~]$ sudo btrfs filesystem df /pool
Data, single: total=8.00MiB, used=64.00KiB
System, RAID1: total=8.00MiB, used=16.00KiB
Metadata, RAID1: total=256.00MiB, used=144.00KiB
GlobalReserve, single: total=3.25MiB, used=0.00B
```

OpenIndiana hipster ZFS:

gparted: without detailed partition list or pool content information

OI

**Comment by raveit65** [comment]
I don't mind because i don't use btrfs after 2 crashes.
Beside from that i prefer to know that a partition is a btrfs-subvolume or a block device, without reading a linux manual.

**Comment by rbuj** [comment]
We can check if the mount has the subvol option using hasmntopt ([ntent.h](https://man7.org/linux/man-pages/man3/getmntent.3.html)) and show the value in a new column.
Note /root is an alias of /.
```C
$ mount | grep btrfs
/dev/sda2 on / type btrfs (rw,relatime,seclabel,ssd,space_cache,subvolid=257,subvol=/root)
/dev/sda2 on /home type btrfs (rw,relatime,seclabel,ssd,space_cache,subvolid=256,subvol=/home)
/dev/sdb on /pool type btrfs (rw,relatime,seclabel,ssd,space_cache,subvolid=5,subvol=/)
/dev/sdb on /pool/new_subvol type btrfs (rw,relatime,seclabel,ssd,space_cache,subvolid=257,subvol=/new_subvol)
/dev/sdb on /pool/snapshot_of_root type btrfs (rw,relatime,seclabel,ssd,space_cache,subvolid=258,subvol=/snapshot_of_root)
```

**Comment by rbuj** [comment]
PR #204

**Review by raveit65 — APPROVED** [review]
Does what it promise,
and builds and runs fine.

**Comment by raveit65** [comment]
cherry-picked to stable branch.
https://github.com/mate-desktop/mate-system-monitor/commit/144afb19d06320612768e506197cd8a22d17f563

**Pull request merged**
