### PR TITLE
disks: implement saving and loading width and visibility of columns

### PR DESCRIPTION
**Pull request by monsta**
@raveit65 @XRevan86 @lukefromdc
please test if you can as this is quite a big change

### CODE REVIEW

**Comment by lukefromdc** [comment]
Column width in the "filesystems" tab was NOT saved between invocations in my test with gtk3.19.11, but mate-system-monitor otherwise worked fine with no obvious problems.

**Comment by lukefromdc** [comment]
Pardon my error-my earlier test was built from the wrong directory and did not contain this code at all! I was very hurried to get to an event. Built it tonight, VERY nice job with more features as well as the saving the view state working very well.

**Comment by raveit65** [comment]
As the commit does not apply on 1.13.1 tarball, i can only test how it works on top of previous changes in master.

**Comment by raveit65** [comment]
Looks good so far, no regression noticed.
But beside from the well known first warning i get some warnings if i move a column.
```
(mate-system-monitor:10345): Gtk-WARNING **: Allocating size to GtkButton 0x5639a3c0eda0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(mate-system-monitor:10345): Gtk-WARNING **: Negative content width -13 (allocation 1, extents 7x7) while allocating gadget (node button, owner GtkButton)


(mate-system-monitor:10345): Gtk-WARNING **: Negative content height -13 (allocation 1, extents 7x7) while allocating gadget (node button, owner GtkButton)


(mate-system-monitor:10345): Gtk-WARNING **: Negative content height -3 (allocation 1, extents 2x2) while allocating gadget (node label, owner GtkLabel)
```
This looks like it is gtk+-3.20 related.

**Comment by raveit65** [comment]
Btw, i suggest to create a new 1.13 release with so much commits since 1.13.1.

**Comment by raveit65** [comment]
Hmm, i noticed that text in some columns not start from the left side.
Not sure, if this is releated to this PR or the other changes, or maybe it was always like this. :)

**Comment by monsta** [comment]
Text in columns with numbers is right-aligned, it was so before.

The warnings seem to be from 3.20 indeed - I don't see them with 3.18.

New dev release can be made of course, I don't mind it :smile:

**Pull request merged**
