### PR TITLE
Dev gtkgrid

### PR DESCRIPTION
**Pull request by raveit65**

### CODE REVIEW

**Comment by monsta** [comment]
Here's how it looks:

m-s-m-visual-issue

**Comment by raveit65** [comment]
Hmm, the graph itself isn't a grid/table, using gtk3-inspector will show you this.
Maybe this is caused by using gtk_widget_set_vexpand (temp_hbox, TRUE); for the GtkGrid below.
This was set before with the GtkTable options.

**Comment by raveit65** [comment]
I love the inspector :-) , setting there vexpand = FALSE for temp_hbox gives me the full graph in real time. I will commit that.

**Comment by raveit65** [comment]
@monsta 
Branch is updated, please test again.

**Comment by monsta** [comment]
All good now :slightly_smiling_face: 

I'd like someone to test it with more processors/cores though (to see how the grid looks with 4 or 8 or more items). I only have an old Core 2 Duo so I can't test that.

**Comment by raveit65** [comment]
With 4 cpus,
normal size:
m-s-m-1
window is titled to the right:
m-s-m-2
window is tiled to the top:
m-s-m-3
maximize:
m-s-m-4
Not really a different to 2 cpus.....well you see 4 cpu color buttons ;-)

**Comment by monsta** [comment]
Looks ok :slightly_smiling_face:

**Pull request merged**
