### PR TITLE
strip surrounding quotes from distro name

### PR DESCRIPTION
**Pull request by rezso**

### CODE REVIEW

**Comment by infirit** [comment]
What if ``s`` does not contain quotes?

**Comment by rezso** [comment]
In the /etc/os-release?

**Comment by infirit** [comment]
Yes, mine has none for ``NAME`` and ``ID``.

**Comment by rezso** [comment]
This function always strips the quotes for the version...
https://github.com/mate-desktop/mate-system-monitor/blob/master/src/sysinfo.cpp#L540

**Comment by infirit** [comment]
Mine has no version :smile:, this is not safe on gentoo. This may be a bug on gentoo but we are making assumptions the string will have quotes, they may not.

```bash
$ cat /etc/os-release 
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"
ANSI_COLOR="1;32"
HOME_URL="http://www.gentoo.org/"
SUPPORT_URL="http://www.gentoo.org/main/en/support.xml"
BUG_REPORT_URL="https://bugs.gentoo.org/"
```

**Comment by infirit** [comment]
>This may be a bug on gentoo

It isn't looking at http://www.freedesktop.org/software/systemd/man/os-release.html

So we will need to check for quotes and then strip them.

**Comment by rezso** [comment]
possible workaround: check the lsb_release first.
https://gist.github.com/rezso/28335e6e768e0d6cf8a9

**Comment by rezso** [comment]
But you are right, really need to check the quotes before strip.

**Pull request closed without merging**
