### PR TITLE
check lsb-release first

### PR DESCRIPTION
**Pull request by rezso**

### CODE REVIEW

**Comment by rezso** [comment]
This is the original order.
http://pkgs.fedoraproject.org/cgit/gnome-system-monitor.git/commit/?id=1ce5a35e4e6664a3107aaa27e5ddcfd12a80a8b5

**Comment by infirit** [comment]
I have no problem with promoting ``lsb-release`` but we are not getting at the real problem. Why do you want to change this and why do you have the need to strip quotes from the ``NAME`` strings?

None of the distro's I have vm's for never use quotes in the name. So I had a look at uhulinux and I see you do use quotes. So why not remove these quotes and follow how the rest of the distro's populate this field.

**Comment by rezso** [comment]
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
NAME="Debian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="http://bugs.debian.org/"

Debian 7 also uses quotes for the NAME in the /etc/os-release. So this is not uhulinux-specific.
About lsb-release: I think, this is a widely used tool. If I check the /etc/lsb-release first, another check is not needed.

**Comment by clefebvre** [comment]
Specific checks need to take priority over generic ones.

In Mint for instance this causes a regression, the lsb-release condition being always TRUE, the code would never evaluate the info from /etc/linuxmint/info.

**Comment by rezso** [comment]
This is Mint issue.
Not to hard to generate a valid /etc/lsb-release file from /etc/linuxmint/info...

**Comment by clefebvre** [comment]
Whether Mint is wrong to store its info in /etc/linuxmint/info or not is off-topic here. That's how it does.

The goal of this piece of code is precisely to adapt to various systems and describe them the best way possible.

**Pull request closed without merging**
