### PR TITLE
CPU colors are selected as equidistant on the hue circle

### PR DESCRIPTION
**Pull request by BrBrRoman**
**Problem:** On systems with a large number of processors, the workload graphs are indistinguishable (e.g. 24 CPU from some video from YouTube).
default

**Solution:** Write CPU color picker algorithm, remove CPU color presets.

**Result:** e.g. my machine 8 CPU default

### CODE REVIEW

**Comment by lukefromdc** [comment]
Here's how it worked out for me:

Master as of 1-4-2018:
master_w_8_cores

With this PR:
pr_w_8_cores

**Comment by raveit65** [comment]
Why removing color presents?
I think most users like to use them with normal consumers cpu.
I am using a amd 8/16 ryzen core and i am very satisfied with using the color presents, because i don't need to change something.
You can use this UI window for picking up any color you want, if you use a highend 32 core proc (amd threadripper).
Simple clicking on the add (+) button in color present window.
bildschirmfoto zu 2019-01-05 11-54-04

**Comment by BrBrRoman** [comment]
> Why removing color presents?
> I think most users like to use them with normal consumers cpu.
> I am using a amd 8/16 ryzen core and i am very satisfied with using the color presents, because i don't need to change something.
> You can use this UI window for picking up any color you want, if you use a highend 32 core proc (amd threadripper).
> Simple clicking on the add (+) button in color present window.
> bildschirmfoto zu 2019-01-05 11-54-04

I didn't know that it possible to pick up colors from UI. Well, the second commit (removing presets) broke this logic and caused the program to crash. Thanks for informing me about it.

**Comment by raveit65** [comment]
I am not really sure that the colors are better visible with my ryzen 1700 (8/16 cores/threads).
The color of the fist 4  cpus looks very similar.
bildschirmfoto zu 2019-01-05 13-23-26

And you broke selecting user colors for the graph!
m-s-m crashes if i select another color, eg. black for cpu1 !
```
(mate-system-monitor:23782): GLib-GIO-ERROR **: 13:28:42.920: Settings schema 'org.mate.system-monitor' does not contain a key named 'cpu-color0'
Trace/breakpoint trap (core dumped)
```
Are you really understand this code?

**Comment by raveit65** [comment]
But i agree that we need more than 16 color presents nowadays.
Highend amd threadripper comes with 32/64 core/threads.

**Comment by BrBrRoman** [comment]
> But i agree that we need more than 16 color presents nowadays.
> Highend amd threadripper comes with 32/64 core/threads.

default

Yes, it seems that my color palette is not the best solution. I'll try to come up with a function for the Value/Brightness component.

**Comment by raveit65** [comment]
Not sure if using more than 16 graphs in one diagram makes sense and all graphs are nice visible, doesn't matter which colors are used.
Maybe we need a second diagram for cpus which needs more than 16 graphs?

**Pull request closed without merging**
