### PR TITLE
reintroduce GTK+2 code and correct some GTK+3 stuff

### PR DESCRIPTION
**Pull request by monsta**

### CODE REVIEW

**Comment by raveit65** [comment]
Looks goog with gtk3 build, but with gtk2 i see some graphical issues.
msn-gtk2
A weird black line athe bottom (with every theme) and columns don't have the right size in process and file-system tabs.
Not sure if this is normal for gtk2 build, i really forgot how it should looks :)

**Comment by raveit65** [comment]
Maybe the blackline is a non expanded box?

**Comment by monsta** [comment]
WTF... had to check previous commits. Well, it turned out I've introduced that earlier (it's there at https://github.com/mate-desktop/mate-system-monitor/commit/6a9264b25f20fe81d837217a6d4875d4e594983f at least). I'll check it later.

**Comment by raveit65** [comment]
With gtk3 it's the GtkStatusbar which displays well in 3.20.
Btw, screenshot how it looks in gtk-3.20 after porting BlueMenta theme.
m-s-m-gtk-3 20
Here the GtkDrawingArea don't displays a white bg. Same with other themes like Adwaita, and i can't set a bg color via theme.
Gnome-system-monitor draws the background color correct, so i guess we need some more fixes from g-s-m.

**Comment by raveit65** [comment]
Btw, we should focus the work to fix this, than a revert of the ftk2 revert isn't needed.
.......sorry, but i didn't expected that the first raw port of BlueMenta works good.

**Comment by raveit65** [comment]
@monsta 
I have a fix for the graph background, m-s-m (gtk3) looks Ok now with gtk3-3.20.
Let us speak tomorrow at irc if this PR is needed or not.

**Comment by monsta** [comment]
Closing as we decided not to keep GTK+2 code after all.

**Pull request closed without merging**
