### PR TITLE
procdialogs: Do not use deprecated gtk_image_new_from_stock

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Review by lukefromdc — COMMENTED** [review]
Builds and doesn't crash on runtime, but both with this and with master I do not get the checkmark "gtk-ok" icon in the dialog, rather I get a return arrow icon. Behavior is exactly the same but implies the icon is being reset-or that I am testing the wrong dialog. To invoke this I am going to change priority->custom which is the only thing that brings up a dialog showing "Change Priority" and "Cancel" buttons I am seeing

**Comment by lukefromdc** [comment]
This is what I am seeing, and changing theme to Menta brings up a similar version of the same icon both with master and with this PR. Is this the wrong dialog?
Change_Priority_Dialog_dialog

**Comment by rbuj** [comment]
@lukefromdc done

Screenshot at 2021-01-22 21-55-23

**Review by lukefromdc — APPROVED** [review]
This now works as expected, and we get the correct icon

**Review by raveit65 — APPROVED** [review]
LGTM

**Pull request merged**
